Repository Automattic/wp-feature-api, pull requests merged in 2025-04, with the labels that each got.

#21 Fix: WP_Feature_Schema_Adapter executes rules with false.
  includes/class-wp-feature-schema-adapter.php
Labels: bug

#18 Add client demo and some basic client side features
  demo/wp-feature-api-demo/includes/Agent/BasicAgent.php
  demo/wp-feature-api-demo/includes/Agent/Message.php
  demo/wp-feature-api-demo/includes/ChatController.php
  demo/wp-feature-api-demo/package-lock.json
  demo/wp-feature-api-demo/package.json
  demo/wp-feature-api-demo/src/chat-app.tsx
  demo/wp-feature-api-demo/src/components/chat-message.tsx
  demo/wp-feature-api-demo/src/context/conversation-provider.tsx
  demo/wp-feature-api-demo/src/globals.d.ts
  demo/wp-feature-api-demo/src/hooks/use-client-action-handler.ts
  demo/wp-feature-api-demo/src/hooks/use-message-handler.ts
  includes/class-wp-feature-schema-adapter.php
  package-lock.json
  package.json
  src/client/features/blocks.ts
  src/client/features/index.ts
  src/client/features/navigation.ts
  src/client/index.ts
  src/client/store/index.ts
  src/client/store/reducer.ts
  src/client/types.ts
  tools/eslint/import-resolver.js
Labels: enhancement

#26 Add Docs
  docs/1.intro.md
  docs/10.demo.md
  docs/2.getting-started.md
  docs/3.registering-features.md
  docs/4.using-features.md
  docs/5.rest-api-endpoints.md
  docs/6.categories.md
  docs/7.advanced-topics.md
  docs/8.extending-contributing.md
  docs/9.mcp.md
  docs/README.md
Labels: documentation
